// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace GameConfigs
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct AvatarRowData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static AvatarRowData GetRootAsAvatarRowData(ByteBuffer _bb) { return GetRootAsAvatarRowData(_bb, new AvatarRowData()); }
  public static AvatarRowData GetRootAsAvatarRowData(ByteBuffer _bb, AvatarRowData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public AvatarRowData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int AvatarId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Type { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Rank { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string Name { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(10); }
  public string Description { get { int o = __p.__offset(12); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDescriptionBytes() { return __p.__vector_as_span<byte>(12, 1); }
#else
  public ArraySegment<byte>? GetDescriptionBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public byte[] GetDescriptionArray() { return __p.__vector_as_array<byte>(12); }
  public string Icon { get { int o = __p.__offset(14); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetIconBytes() { return __p.__vector_as_span<byte>(14, 1); }
#else
  public ArraySegment<byte>? GetIconBytes() { return __p.__vector_as_arraysegment(14); }
#endif
  public byte[] GetIconArray() { return __p.__vector_as_array<byte>(14); }
  public int ExchangeValue(int j) { int o = __p.__offset(16); return o != 0 ? __p.bb.GetInt(__p.__vector(o) + j * 4) : (int)0; }
  public int ExchangeValueLength { get { int o = __p.__offset(16); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<int> GetExchangeValueBytes() { return __p.__vector_as_span<int>(16, 4); }
#else
  public ArraySegment<byte>? GetExchangeValueBytes() { return __p.__vector_as_arraysegment(16); }
#endif
  public int[] GetExchangeValueArray() { return __p.__vector_as_array<int>(16); }

  public static Offset<GameConfigs.AvatarRowData> CreateAvatarRowData(FlatBufferBuilder builder,
      int AvatarId = 0,
      int Type = 0,
      int Rank = 0,
      StringOffset NameOffset = default(StringOffset),
      StringOffset DescriptionOffset = default(StringOffset),
      StringOffset IconOffset = default(StringOffset),
      VectorOffset ExchangeValueOffset = default(VectorOffset)) {
    builder.StartTable(7);
    AvatarRowData.AddExchangeValue(builder, ExchangeValueOffset);
    AvatarRowData.AddIcon(builder, IconOffset);
    AvatarRowData.AddDescription(builder, DescriptionOffset);
    AvatarRowData.AddName(builder, NameOffset);
    AvatarRowData.AddRank(builder, Rank);
    AvatarRowData.AddType(builder, Type);
    AvatarRowData.AddAvatarId(builder, AvatarId);
    return AvatarRowData.EndAvatarRowData(builder);
  }

  public static void StartAvatarRowData(FlatBufferBuilder builder) { builder.StartTable(7); }
  public static void AddAvatarId(FlatBufferBuilder builder, int AvatarId) { builder.AddInt(0, AvatarId, 0); }
  public static void AddType(FlatBufferBuilder builder, int Type) { builder.AddInt(1, Type, 0); }
  public static void AddRank(FlatBufferBuilder builder, int Rank) { builder.AddInt(2, Rank, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset NameOffset) { builder.AddOffset(3, NameOffset.Value, 0); }
  public static void AddDescription(FlatBufferBuilder builder, StringOffset DescriptionOffset) { builder.AddOffset(4, DescriptionOffset.Value, 0); }
  public static void AddIcon(FlatBufferBuilder builder, StringOffset IconOffset) { builder.AddOffset(5, IconOffset.Value, 0); }
  public static void AddExchangeValue(FlatBufferBuilder builder, VectorOffset ExchangeValueOffset) { builder.AddOffset(6, ExchangeValueOffset.Value, 0); }
  public static VectorOffset CreateExchangeValueVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateExchangeValueVectorBlock(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartExchangeValueVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<GameConfigs.AvatarRowData> EndAvatarRowData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<GameConfigs.AvatarRowData>(o);
  }
};

public struct Avatar : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static Avatar GetRootAsAvatar(ByteBuffer _bb) { return GetRootAsAvatar(_bb, new Avatar()); }
  public static Avatar GetRootAsAvatar(ByteBuffer _bb, Avatar obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Avatar __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public GameConfigs.AvatarRowData? Datalist(int j) { int o = __p.__offset(4); return o != 0 ? (GameConfigs.AvatarRowData?)(new GameConfigs.AvatarRowData()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int DatalistLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<GameConfigs.Avatar> CreateAvatar(FlatBufferBuilder builder,
      VectorOffset datalistOffset = default(VectorOffset)) {
    builder.StartTable(1);
    Avatar.AddDatalist(builder, datalistOffset);
    return Avatar.EndAvatar(builder);
  }

  public static void StartAvatar(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddDatalist(FlatBufferBuilder builder, VectorOffset datalistOffset) { builder.AddOffset(0, datalistOffset.Value, 0); }
  public static VectorOffset CreateDatalistVector(FlatBufferBuilder builder, Offset<GameConfigs.AvatarRowData>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateDatalistVectorBlock(FlatBufferBuilder builder, Offset<GameConfigs.AvatarRowData>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartDatalistVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<GameConfigs.Avatar> EndAvatar(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<GameConfigs.Avatar>(o);
  }
  public static void FinishAvatarBuffer(FlatBufferBuilder builder, Offset<GameConfigs.Avatar> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedAvatarBuffer(FlatBufferBuilder builder, Offset<GameConfigs.Avatar> offset) { builder.FinishSizePrefixed(offset.Value); }
};


}
