// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace GameConfigs
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct BulletRowData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static BulletRowData GetRootAsBulletRowData(ByteBuffer _bb) { return GetRootAsBulletRowData(_bb, new BulletRowData()); }
  public static BulletRowData GetRootAsBulletRowData(ByteBuffer _bb, BulletRowData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public BulletRowData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string Resource { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetResourceBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetResourceBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetResourceArray() { return __p.__vector_as_array<byte>(6); }
  public int BulletEffectId { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int HitEffectId { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public float BulletSpeed { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float BeginTime { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public int Num { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public float Interval { get { int o = __p.__offset(18); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float EndTime { get { int o = __p.__offset(20); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static Offset<GameConfigs.BulletRowData> CreateBulletRowData(FlatBufferBuilder builder,
      int Id = 0,
      StringOffset ResourceOffset = default(StringOffset),
      int BulletEffectId = 0,
      int HitEffectId = 0,
      float BulletSpeed = 0.0f,
      float BeginTime = 0.0f,
      int Num = 0,
      float Interval = 0.0f,
      float EndTime = 0.0f) {
    builder.StartTable(9);
    BulletRowData.AddEndTime(builder, EndTime);
    BulletRowData.AddInterval(builder, Interval);
    BulletRowData.AddNum(builder, Num);
    BulletRowData.AddBeginTime(builder, BeginTime);
    BulletRowData.AddBulletSpeed(builder, BulletSpeed);
    BulletRowData.AddHitEffectId(builder, HitEffectId);
    BulletRowData.AddBulletEffectId(builder, BulletEffectId);
    BulletRowData.AddResource(builder, ResourceOffset);
    BulletRowData.AddId(builder, Id);
    return BulletRowData.EndBulletRowData(builder);
  }

  public static void StartBulletRowData(FlatBufferBuilder builder) { builder.StartTable(9); }
  public static void AddId(FlatBufferBuilder builder, int Id) { builder.AddInt(0, Id, 0); }
  public static void AddResource(FlatBufferBuilder builder, StringOffset ResourceOffset) { builder.AddOffset(1, ResourceOffset.Value, 0); }
  public static void AddBulletEffectId(FlatBufferBuilder builder, int BulletEffectId) { builder.AddInt(2, BulletEffectId, 0); }
  public static void AddHitEffectId(FlatBufferBuilder builder, int HitEffectId) { builder.AddInt(3, HitEffectId, 0); }
  public static void AddBulletSpeed(FlatBufferBuilder builder, float BulletSpeed) { builder.AddFloat(4, BulletSpeed, 0.0f); }
  public static void AddBeginTime(FlatBufferBuilder builder, float BeginTime) { builder.AddFloat(5, BeginTime, 0.0f); }
  public static void AddNum(FlatBufferBuilder builder, int Num) { builder.AddInt(6, Num, 0); }
  public static void AddInterval(FlatBufferBuilder builder, float Interval) { builder.AddFloat(7, Interval, 0.0f); }
  public static void AddEndTime(FlatBufferBuilder builder, float EndTime) { builder.AddFloat(8, EndTime, 0.0f); }
  public static Offset<GameConfigs.BulletRowData> EndBulletRowData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<GameConfigs.BulletRowData>(o);
  }
};

public struct Bullet : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static Bullet GetRootAsBullet(ByteBuffer _bb) { return GetRootAsBullet(_bb, new Bullet()); }
  public static Bullet GetRootAsBullet(ByteBuffer _bb, Bullet obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Bullet __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public GameConfigs.BulletRowData? Datalist(int j) { int o = __p.__offset(4); return o != 0 ? (GameConfigs.BulletRowData?)(new GameConfigs.BulletRowData()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int DatalistLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<GameConfigs.Bullet> CreateBullet(FlatBufferBuilder builder,
      VectorOffset datalistOffset = default(VectorOffset)) {
    builder.StartTable(1);
    Bullet.AddDatalist(builder, datalistOffset);
    return Bullet.EndBullet(builder);
  }

  public static void StartBullet(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddDatalist(FlatBufferBuilder builder, VectorOffset datalistOffset) { builder.AddOffset(0, datalistOffset.Value, 0); }
  public static VectorOffset CreateDatalistVector(FlatBufferBuilder builder, Offset<GameConfigs.BulletRowData>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateDatalistVectorBlock(FlatBufferBuilder builder, Offset<GameConfigs.BulletRowData>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartDatalistVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<GameConfigs.Bullet> EndBullet(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<GameConfigs.Bullet>(o);
  }
  public static void FinishBulletBuffer(FlatBufferBuilder builder, Offset<GameConfigs.Bullet> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedBulletBuffer(FlatBufferBuilder builder, Offset<GameConfigs.Bullet> offset) { builder.FinishSizePrefixed(offset.Value); }
};


}
