// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace GameConfigs
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct RoomExclusiveRowData : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static RoomExclusiveRowData GetRootAsRoomExclusiveRowData(ByteBuffer _bb) { return GetRootAsRoomExclusiveRowData(_bb, new RoomExclusiveRowData()); }
  public static RoomExclusiveRowData GetRootAsRoomExclusiveRowData(ByteBuffer _bb, RoomExclusiveRowData obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public RoomExclusiveRowData __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int ExclusiveId { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int BuffId { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string BuffName { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetBuffNameBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetBuffNameBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetBuffNameArray() { return __p.__vector_as_array<byte>(8); }
  public string BuffDesc { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetBuffDescBytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetBuffDescBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetBuffDescArray() { return __p.__vector_as_array<byte>(10); }
  public string BuffIcon { get { int o = __p.__offset(12); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetBuffIconBytes() { return __p.__vector_as_span<byte>(12, 1); }
#else
  public ArraySegment<byte>? GetBuffIconBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public byte[] GetBuffIconArray() { return __p.__vector_as_array<byte>(12); }
  public int BuffMark { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int BuffValue { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int BuffDuration { get { int o = __p.__offset(18); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Weight { get { int o = __p.__offset(20); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<GameConfigs.RoomExclusiveRowData> CreateRoomExclusiveRowData(FlatBufferBuilder builder,
      int ExclusiveId = 0,
      int BuffId = 0,
      StringOffset BuffNameOffset = default(StringOffset),
      StringOffset BuffDescOffset = default(StringOffset),
      StringOffset BuffIconOffset = default(StringOffset),
      int BuffMark = 0,
      int buffValue = 0,
      int BuffDuration = 0,
      int Weight = 0) {
    builder.StartTable(9);
    RoomExclusiveRowData.AddWeight(builder, Weight);
    RoomExclusiveRowData.AddBuffDuration(builder, BuffDuration);
    RoomExclusiveRowData.AddBuffValue(builder, buffValue);
    RoomExclusiveRowData.AddBuffMark(builder, BuffMark);
    RoomExclusiveRowData.AddBuffIcon(builder, BuffIconOffset);
    RoomExclusiveRowData.AddBuffDesc(builder, BuffDescOffset);
    RoomExclusiveRowData.AddBuffName(builder, BuffNameOffset);
    RoomExclusiveRowData.AddBuffId(builder, BuffId);
    RoomExclusiveRowData.AddExclusiveId(builder, ExclusiveId);
    return RoomExclusiveRowData.EndRoomExclusiveRowData(builder);
  }

  public static void StartRoomExclusiveRowData(FlatBufferBuilder builder) { builder.StartTable(9); }
  public static void AddExclusiveId(FlatBufferBuilder builder, int ExclusiveId) { builder.AddInt(0, ExclusiveId, 0); }
  public static void AddBuffId(FlatBufferBuilder builder, int BuffId) { builder.AddInt(1, BuffId, 0); }
  public static void AddBuffName(FlatBufferBuilder builder, StringOffset BuffNameOffset) { builder.AddOffset(2, BuffNameOffset.Value, 0); }
  public static void AddBuffDesc(FlatBufferBuilder builder, StringOffset BuffDescOffset) { builder.AddOffset(3, BuffDescOffset.Value, 0); }
  public static void AddBuffIcon(FlatBufferBuilder builder, StringOffset BuffIconOffset) { builder.AddOffset(4, BuffIconOffset.Value, 0); }
  public static void AddBuffMark(FlatBufferBuilder builder, int BuffMark) { builder.AddInt(5, BuffMark, 0); }
  public static void AddBuffValue(FlatBufferBuilder builder, int buffValue) { builder.AddInt(6, buffValue, 0); }
  public static void AddBuffDuration(FlatBufferBuilder builder, int BuffDuration) { builder.AddInt(7, BuffDuration, 0); }
  public static void AddWeight(FlatBufferBuilder builder, int Weight) { builder.AddInt(8, Weight, 0); }
  public static Offset<GameConfigs.RoomExclusiveRowData> EndRoomExclusiveRowData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<GameConfigs.RoomExclusiveRowData>(o);
  }
};

public struct RoomExclusive : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static RoomExclusive GetRootAsRoomExclusive(ByteBuffer _bb) { return GetRootAsRoomExclusive(_bb, new RoomExclusive()); }
  public static RoomExclusive GetRootAsRoomExclusive(ByteBuffer _bb, RoomExclusive obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public RoomExclusive __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public GameConfigs.RoomExclusiveRowData? Datalist(int j) { int o = __p.__offset(4); return o != 0 ? (GameConfigs.RoomExclusiveRowData?)(new GameConfigs.RoomExclusiveRowData()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int DatalistLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<GameConfigs.RoomExclusive> CreateRoomExclusive(FlatBufferBuilder builder,
      VectorOffset datalistOffset = default(VectorOffset)) {
    builder.StartTable(1);
    RoomExclusive.AddDatalist(builder, datalistOffset);
    return RoomExclusive.EndRoomExclusive(builder);
  }

  public static void StartRoomExclusive(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddDatalist(FlatBufferBuilder builder, VectorOffset datalistOffset) { builder.AddOffset(0, datalistOffset.Value, 0); }
  public static VectorOffset CreateDatalistVector(FlatBufferBuilder builder, Offset<GameConfigs.RoomExclusiveRowData>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateDatalistVectorBlock(FlatBufferBuilder builder, Offset<GameConfigs.RoomExclusiveRowData>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartDatalistVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<GameConfigs.RoomExclusive> EndRoomExclusive(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<GameConfigs.RoomExclusive>(o);
  }
  public static void FinishRoomExclusiveBuffer(FlatBufferBuilder builder, Offset<GameConfigs.RoomExclusive> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedRoomExclusiveBuffer(FlatBufferBuilder builder, Offset<GameConfigs.RoomExclusive> offset) { builder.FinishSizePrefixed(offset.Value); }
};


}
